name: Deploy stage
on:
  push:
    branches: [ "main" ]    

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.STAGE }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_STAGE }}
        port: 443
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
